/* Generated by honey codegen-mcp.ts — do not edit by hand. */

import { AnyrowSDK } from "@anyrow/sdk"
import { createMCPServer } from "./_runtime"
import { buildTools } from "./tools.gen"

const apiKey = process.env["ANYROW_API_KEY"] ?? ""
const baseURL = process.env["ANYROW_BASE_URL"] ?? "https://api.anyrow.com"

const sdk = new AnyrowSDK({
	baseURL,
	headers: apiKey.length > 0 ? { Authorization: `Bearer ${apiKey}` } : {},
	throwOnError: true,
})

const tools = buildTools(sdk as unknown as Record<string, unknown>)

await createMCPServer({
	sdk,
	serverInfo: { name: "Anyrow API", version: "0.1.0" },
	tools,
})
